apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
 name: vault-pg-secret
 namespace: default
spec:
 provider: vault
 parameters:
   vaultAddress: "http://vault.vault.svc.cluster.local:8200"
   roleName: "vault-role"
   objects: |
     - objectName: "username"
       secretPath: "secret/data/pg-secret"
       secretKey: "username"
     - objectName: "password"
       secretPath: "secret/data/pg-secret"
       secretKey: "password"
 secretObjects:                       # <- this enables syncing
 - secretName: pg-secret-k8s        # Kubernetes Secret name to create
   type: Opaque
   data:
     - objectName: username
       key: username
     - objectName: password
       key: password